# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/
$ ->
    but = $("<button>").addClass(".but").text("I HAVE SOMETHING TO SAY!")
    but.css "display", "block"
    but.css "color", "blue"
    but.on("click", (event) ->
        msg = new SpeechSynthesisUtterance('Leave me alone')
        window.speechSynthesis.speak new SpeechSynthesisUtterance('Leave me alone')
        $("#shakeme").text("Clicked!")
        setTimeout (->
            $("#shakeme").text("ᕦ(ò_ó)ᕤ")
        ), 1000
    )
    $("#alone").append(but)
    deviceMotionHandler = (eventData) ->
        if eventData.acceleration.x > 2 or eventData.acceleration.y > 2 or eventData.acceleration.z > 2
            $("#shakeme").addClass("hover")
            $("#shakeme").text("YAY!")
            $("#alone").append(but)
            setTimeout (->
                $("#shakeme").removeClass("hover")
            ), 1000
    
    if (window.DeviceMotionEvent)
        console.log("DeviceMotionEvent supported")
        window.addEventListener('devicemotion', deviceMotionHandler, false)

# ___________________________________________________________________________________
    video = document.getElementById('video')
    canvas = document.getElementById('canvas')
    context = canvas.getContext('2d')
    
    streamWebCam = (stream) ->
        video.src = window.URL.createObjectURL(stream)
        video.play()
    
    throwError = (e) ->
        alert e.name

    snap = ->
        canvas.width = video.clientWidth
        canvas.height = video.clientHeight
        context.drawImage video, 0, 0
        console.log "here :("
    $("#snap").on("click", snap)
    
    navigator.getUserMedia = navigator.getUserMedia or navigator.webkitGetUserMedia or navigator.mozGetUserMedia or navigator.oGetUserMedia or navigator.msGetUserMedia
    if navigator.getUserMedia
        navigator.getUserMedia { video: true }, streamWebCam, throwError
    

    if (window.DeviceMotionEvent)
        console.log("DeviceMotionEvent supported")




# ---
# generated by js2coffee 2.2.0